POST http://127.0.0.1:4001/home/register HTTP/1.1
content-type: application/json


{
    "first_name": "archit",
    "last_name": "jain",
    "email": "arcyjain2002@gmail.com",
    "password": "Password1"
}


###


POST http://127.0.0.1:4001/home/register HTTP/1.1
content-type: application/json


{
    "first_name": "john",
    "last_name": "doe",
    "email": "example@example.com",
    "password": "helloworld"
}


###

POST http://127.0.0.1:4001/home/login HTTP/1.1
content-type: application/json


{
    "email": "arcyjain2002@gmail.com",
    "password": "Password1"
}


###

POST http://127.0.0.1:4001/home/login HTTP/1.1
content-type: application/json


{
    "email": "example@example.com",
    "password": "helloworld"
}


###


GET http://127.0.0.1:4001/home/post HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjJhZGUyNTNjMzA1NmQzNWM4MzA4ZTMxIiwiZW1haWwiOiJhcmN5amFpbjIwMDJAZ21haWwuY29tIiwiaWF0IjoxNjU1NTcxNDUxLCJleHAiOjE2NTU1Nzg2NTF9.WPEKC6jAahr8H-BXXbqDC8imUrIuNlCod-AUloacYn0

###

